### ISSUE TITLE
wont stop as a user thread keeps alive

### ISSUE THREAD

**Issue by littleboyonearth** [dustinkredmond/FXTrayIcon#11]
![image](https://user-images.githubusercontent.com/19209493/109298306-543dbd00-786e-11eb-93b9-2f3a5f77b562.png)

the new thread is not a daemon thread, so it will prevent the application from exiting

**Comment by dustinkredmond** [comment]
@littleboyonearth In the latest version of FXTrayIcon, we do not use this `Thread` anymore. The check is instead done by invoking `EventQueue.invokeLater()` this way we can check on that particular thread, so there's no timing issue.

Please update your fork/clone to the latest version. Thanks!
