### ISSUE TITLE
[Feature Request] Restructure Builder class to support extended FXTrayIcon classes.

### ISSUE THREAD

**Issue by Nex-Coder** [dustinkredmond/FXTrayIcon#25]
I'm trying to extend FXTrayIcon to allow (in addtion) for a custom Menu when righitng clicking. 

I can do that fine with some reflection to get the trayIcon (all though would be nice if it was protected :D)
However, supporting the builder in my extended even with some nasty reflection just isn't do-able i think because it always returns a FXTrayIcon constructed as such instead of my custom class. I'd have to copy your wonderful code and that just doesn't feel right.

I tried settings it with reflection in the builder but its final so no bueno.

Would it be possible to Generify builder? or make the trayIcon field (in the builder) protected and not final?

Love the work btw!  <3 🥇

**Comment by Nex-Coder** [comment]
Hey, Sorry for getting back so late. Had a pretty spooky halloween ;) But ive now had the chance to have a look at the new implemtnation and doesn't allow construction of the custom class.

Because the Build constructor is private in FXTrayIcon it can't be used in sub classes. 
Also, the fields are private in the base FXTrayIcon.Builder so they can't be used in another implementation from scratch that implements this functionality..
Also, the builder() function so returns a constructed instance of FXTrayIcon so the return can't be used either directly.

The ways i see overcoming this is either providing protected getters for the fields so we can construct our own instances of FXTrayIcon when overriding build(). This also allows us the implement our own constructor that takes a builder.

or on the other hand

the previous protected trayIcon also would work but i think we could both agree that the previous solution works better overall.

**Comment by Nex-Coder** [comment]
Yeah, I did try some examples. I'll try again when I get some time later, working again. :D 

But i kept getting errors  like "Cannot cast FXTrayIcon to NexTrayIcon" etc. Both extending and using the base builder. :)

**Comment by Nex-Coder** [comment]
Here we are @EasyG0ing1!
So, for example. If i try to use this extended builder (in my extend class of FXTrayIcon)...

```java
    public static class Builder extends FXTrayIcon.Builder {

        public Builder(Stage parentStage, URL iconImagePath, int iconWidth, int iconHeight) {
            super(parentStage, iconImagePath, iconWidth, iconHeight);
        }

        public Builder(Stage parentStage, URL iconImagePath) {
            super(parentStage, iconImagePath);
        }

        public Builder(Stage parentStage) {
            super(parentStage);
        }
        
        @Override public NexTrayIcon.Builder menuItem(String label, EventHandler<ActionEvent> eventHandler) { return (Builder) super.menuItem(label, eventHandler); }
        @Override public NexTrayIcon.Builder menuItem(javafx.scene.control.MenuItem menuItem) { return (Builder) super.menuItem(menuItem); }
        @Override public NexTrayIcon.Builder menuItems(javafx.scene.control.MenuItem... menuItems) { return (Builder) super.menuItems(menuItems); }
        @Override public NexTrayIcon.Builder separator() { return (Builder) super.separator(); }
        @Override public NexTrayIcon.Builder toolTip(String tooltip) { return (Builder) super.toolTip(tooltip); }
        @Override public NexTrayIcon.Builder addTitleItem(boolean addTitleMenuItem) { return (Builder) super.addTitleItem(addTitleMenuItem); }
        @Override public NexTrayIcon.Builder applicationTitle(String appTitle) { return (Builder) super.applicationTitle(appTitle); }
        @Override public NexTrayIcon.Builder addExitMenuItem() { return (Builder) super.addExitMenuItem(); }
        @Override public NexTrayIcon.Builder onAction(EventHandler<ActionEvent> event) { return (Builder) super.onAction(event); }
        @Override public NexTrayIcon.Builder show() { return (Builder) super.show(); }

        @Override
        public NexTrayIcon build() {
            this.isMac = System.getProperty("os.name").toLowerCase(Locale.ENGLISH).contains("mac");
            if (this.iconWidth == 0 || this.iconHeight == 0) {
                if (this.isMac) {
                    this.iconWidth = 26;
                    this.iconHeight = 26;
                } else {
                    this.iconWidth = 16;
                    this.iconHeight = 16;
                }
            }

            if (this.useDefaultIcon) {
                this.icon = FXTrayIcon.loadImageFromFile(this.defaultIconPath, this.iconWidth, this.iconHeight);
            } else {
                this.icon = FXTrayIcon.loadImageFromFile(this.iconImagePath, this.iconWidth, this.iconHeight);
            }

            return new NexTrayIcon(this);
        }
    }
```

and construct like so

```java
   NexTrayIcon icon = new NexTrayIcon.Builder(stage, url).build();
```

It will not work because the fields inside the super class builder are all private with no way to access them and thus no way of passing the fields to the private constructor in my extended FXTrayIcon called `NexTrayIcon`. :)

Admittedly, the concept of private constructors is new to me so maybe im goofing up somewhere. Nether the less I get

`
error: isMac has private access in Builder this.isMac = System.getProperty("os.name").toLowerCase(Locale.ENGLISH).contains("mac");
`

on compile.

Obviously, whenever I've implemented my custom features for FXTrayIcon, i could add any related properties to my extended Builder for the constructor, but I just want to show the basics of course.

**Comment by Nex-Coder** [comment]
Okay, so this has been a bit of a learning experience for me. And I now know that all i really needed to do in my builder was this... 

```java 
        @Override
        public NexTrayIcon build() {
            return new NexTrayIcon(this);
        }
```

and my private constructor can then look like this

```java
    private NexTrayIcon(Builder builder) {
        super(builder);
        this.customField = builder.customField; // my custom fields assigned here
    }
```

but this still leave one last problem. The constructor in super is still private :D 

I think the only change that needs to be done in your new implementation to support extended builders is a going from a private consturctor of FXTrayIcon to a protected one. 

When private, it ensures derivaed classes cannot construct from it. But with protected classes, derivaed classes are support and no encapsulation is broken :)

Problem solved unless you have any problems

**Comment by dustinkredmond** [comment]
I'm not averse to making the constructor protected. I will try to review this today. Thanks!

**Comment by Nex-Coder** [comment]
Great @dustinkredmond!

I've setup a fork with those two changes (newbuilder & protected constrctor).

Also. I added a protected getter for the AWT trayIcon. This would just be a nice bonus as corrently I'm using reflection to get and use it for custom things. 
I plan add stuff like animated trayIcon, custom right clcik menu, etc. So it would be really great if we could get this too! Reflection works but its less than idea haha.

I've made a fork [here](https://github.com/Nex-Coder/FXTrayIcon) if you like the sound of all that :) i can open a pull request :)

**Comment by EasyG0ing1** [comment]
@dustinkredmond - I looked at his fork, and I made trayIcon protected as well as the private constructor for the Builder class in my existing pull request. It looks like those were the only two changes he made.

@Nex-Coder you can see the branch where I implemented your changes [here](https://github.com/EasyG0ing1/FXTrayIcon/tree/ProperBuilder), take a look and see if it's right.

**Comment by Nex-Coder** [comment]
@EasyG0ing1 Yeah that all I wished for thanks! Only difference being i made a protected final getter for trayIcon. But its exactly the same result! That satisfies everything an extended implemtnation needs on my end.

**Comment by EasyG0ing1** [comment]
@Nex-Coder I added the getter to the branch as well. It is locked and loaded in the current pull request.

**Comment by EasyG0ing1** [comment]
@Nex-Coder - Here is an artifact that includes all of the changes if you want to test it.

[FXTrayIcon.zip](https://github.com/dustinkredmond/FXTrayIcon/files/7468270/FXTrayIcon.zip)

**Comment by Nex-Coder** [comment]
I can confirm the new changes permit extended classes!!! 
Test some building and changes in super() calls are also visable in the current this().

Feel free to close this thread once your done tracking/pushed to mavern. <3

**Comment by EasyG0ing1** [comment]
The ball is in @dustinkredmond 's court right now. Everything is done, just needs to be merged and (hopefully) published.

**Comment by EasyG0ing1** [comment]
@Nex-Coder You mentioned something about animated icons in the tray ... I'd like to see that in action...

:-)

**Comment by Nex-Coder** [comment]
Sure. I can work this stuff in a fork if you guys like and contribute the features you guys want :) 
Not exactly sure how far I will take it, but I know I'd like some custom right click parents/controls and semi animated icons. Like Discords microphone activatity TrayIcon.

**Comment by EasyG0ing1** [comment]
@Nex-Coder Well I know that FXTrayIcon is a native AWT control because there STILL does not exist, a native JavaFX System Tray Icon object, in spite of it being officially requested and receiving enough votes for its implementation into JavaFX back in ... 2015 I believe. It even had a developer assigned to it ... but it seems that person had better things to do.

Anyways, The reason I mention the AWT fact of our reality is that where Macs are concerned, right-clicking is an exercise in futility. HOWEVER, we can dual click on it and get some action from it that way ... Windows is another story, you can right click on it all day in Windows ... if fact, I don't think there is any difference between a right-click in Windows vs a left-click ... which is fun ... 

If you start developing something that begins to have a shape to it, let me know... perhaps you could just post it on your Github page and I could clone it from there and have a look.

My email, by the way, is sims.mike@gmail.com
