### ISSUE TITLE
Show Popup Menu with left click

### ISSUE THREAD

**Issue by hrzafer** [dustinkredmond/FXTrayIcon#28]
Hi,

Currently, the tray icon shows the menu only when right-clicked. How can we change this behavior so that it does the same with a left click.

Thanks

**Comment by EasyG0ing1** [comment]
@hrzafer - Which operating system are you using? If you're using a mac, try clicking with left and right buttons at the same time.

**Comment by hrzafer** [comment]
I'm using Windows 11. FxTrayIcon works as expected. My question is can I make it show the menu with a left-click instead of a right-click.

**Comment by EasyG0ing1** [comment]
No, I believe it is a limitation in AWT ... well... you COULD get it to work with the jeft button, but you would need to running MacOS.  ;-)

**Comment by dustinkredmond** [comment]
Closing due to the further discussion and explanation on this subject on Issue #30. Any updates will be provided on that issue.
