### ISSUE TITLE
Text instead of icon

### ISSUE THREAD

**Issue by HanSolo** [dustinkredmond/FXTrayIcon#35]
Hi there,

Just a short question/feature request...would it be possible to have a text in the tray icon instead of an icon? Would be nice to have the ability to set/change text in the system tray.

**Comment by dustinkredmond** [comment]
@HanSolo To clarify, I think you are asking about text in the place of the icon graphic.

The underlying AWT implementation, to my knowledge, does not support this. I think we would have to (at runtime) generate a graphic with the text, then save to disk and pass it to the AWT API.

If this is a requirement of your program, I think it best that you provide the text (as a JavaFX Image) to `FXTrayIcon`. If we try to do this automatically based on a passed in `String` it would add a lot of overhead to `FXTrayIcon`, and frankly, I wouldn't know where to start. For starters, the image would have to look appealing on the OSes supported by FXTrayIcon, as well as look good given the resolution of the user's PC as well as their scaling. Also, we'd need to worry about high DPI displays. 

If you've seen another Java application (or any language for that matter) that pulls this off, I would love to take a look at that code. 😄

**Comment by HanSolo** [comment]
Yep I already checked and saw that it‘s not supported. I‘m currently replacing a Swift app with an FX app and the Swift app can place text in the tray icon. Will try creating images but they might look to blurry. Will check…thx for the response 👍🏻
