### ISSUE TITLE
Popup without sound

### ISSUE THREAD

**Issue by PULSO-Gloves** [dustinkredmond/FXTrayIcon#38]
Can we do this?

**Comment by dustinkredmond** [comment]
@PULSO-Gloves unfortunately, this is not possible by using the FXTrayIcon library, as it just calls built-in AWT and JavaFX methods. You would have to research whether AWT and/or JavaFX allow this, but I would guess that this is handled by the desktop environment of whatever operating system you are using.

**Comment by EasyG0ing1** [comment]
@PULSO-Gloves You might be able to assign an event listener of some kind to the TrayIcon then fire off an audio file when the event is triggered... but I'm only making an educated guess without any attempt at trying it myself.
