### ISSUE TITLE
Builder API inconsistent

### ISSUE THREAD

**Issue by dwalluck** [dustinkredmond/FXTrayIcon#42]
Why is ` URL iconImagePath` required to be passed into the builder constructor and not via a method? If the idea is to put required arguments in the constructor, then this doesn't make sense because there's a `setGraphic()` method, but no corresponding `graphic()` method for the builder. I see that it is probably to match the existing non-builder constructors, but I still think there should be a `graphic()`  method and possibly others for the size. In any case, it seems a good idea to have the builders constructors and methods match the original, if possible.

The API is `setTooltip()`, but `toolTip()` in the builder, whereas I think it should be `tooltip()`.  It seems to be an inconsistency in AWT vs. JavaFX naming. I believe the AWT method uses a capital 'T', but JavaFX uses a lowercase 't' by convention.

There's a `setTrayIconTooltip()` API which does the same thing, but the builder doesn't have such a method.

**Comment by dustinkredmond** [comment]
Hi @dwalluck , the Builder API is still relatively new, we'll check on standardizing this to match the JavaFX convention.

**Comment by dustinkredmond** [comment]
@EasyG0ing1, would you have time to review this? Since it changes public API, it's not an immediate necessity, but would be a "nice-to-have" for the next major release.

**Comment by EasyG0ing1** [comment]
@dwalluck - I just now caught the mention of the tooltip thing in the builder ... I did submit a PR for it though it seems a little nit-picky at this point ... I also wanted to point out that this is the published method in the official```java.awt TrayIcon``` class...
<img width="662" alt="Screen Shot 2022-05-11 at 7 14 34 AM" src="https://user-images.githubusercontent.com/10106834/167872647-115b68d8-209b-46b5-86e4-1c1e7800d1fb.png">


... just saying ... ☺

**Comment by EasyG0ing1** [comment]
@dwalluck  - Also, check out PR #47

**Comment by dustinkredmond** [comment]
Going with @EasyG0ing1's PR and closing this. Feel free to re-open if any further discussion.

**Comment by dwalluck** [comment]
> @dwalluck - I just now caught the mention of the tooltip thing in the builder ... I did submit a PR for it though it seems a little nit-picky at this point ... I also wanted to point out that this is the published method in the official`java.awt TrayIcon` class... <img alt="Screen Shot 2022-05-11 at 7 14 34 AM" width="662" src="https://user-images.githubusercontent.com/10106834/167872647-115b68d8-209b-46b5-86e4-1c1e7800d1fb.png">
> 
> ... just sayin' ... ☺

Yes, I know.

One of my original "complaints" was that the AWT methods have different naming conventions from JavaFX, and it's a JavaFX library. To me, it makes sense to align with JavaFX naming conventions, not AWT.

On top of that, the builder methods didn't match the get/set methods.

But, yes, as it deals with naming you could call it "nit-picky".

**Comment by EasyG0ing1** [comment]
@dwalluck - I mean on one side of the fence ... it's nit-picking ... but on the other side of the fence, when you're reading code and trying to make sense of it, the last thing you need, are brain obstacles on the screen that distract from the main goal - understanding the code!

I actually have been ACTIVELY forcing myself to use the word filename and not fileName ... because technically, it's one word. But even after months of catching myself and correcting myself, I still find that I sometimes use fileName without even thinking ... it's the little things that matter sometimes.  ☺
