### ISSUE TITLE
Support for RadioMenuItems

### ISSUE THREAD

**Issue by azplanlos** [dustinkredmond/FXTrayIcon#51]
It would be very nice to have support for CheckMenuItem and RadioMenuItem to allow users to toggle select in the tray icon menu.

**Comment by EasyG0ing1** [comment]
@azplanlos - This is an interesting suggestion ... however, this won't work, and here is why...

JavaFX MenuItems are CONVERTED over to an AWT framework before they are added to the FXTrayIcon popup menu. And since they technically are not rendered as JavaFX objects, there is no hope of implementing a full-flavored JavaFX object within FXTray Icon. 

Maybe one day, JavaFX will actually support the System Tray, but until that day comes, this is the best we got.

**Comment by azplanlos** [comment]
I implemented a version supporting CheckMenuItems and will create a pull request shortly.
________________________________
Von: Michael Sims ***@***.***>
Gesendet: Wednesday, May 11, 2022 4:01:17 PM
An: dustinkredmond/FXTrayIcon ***@***.***>
Cc: Andreas Zöllner ***@***.***>; Mention ***@***.***>
Betreff: Re: [dustinkredmond/FXTrayIcon] Support for RadioMenuItems (Issue #51)


@azplanlos<https://github.com/azplanlos> - This is an interesting suggestion ... however, this won't work, and here is why...

JavaFX MenuItems are CONVERTED over to an AWT framework before they are added to the FXTrayIcon popup menu. And since they technically are not rendered as JavaFX objects, there is no hope of implementing a full-flavored JavaFX object within FXTray Icon.

Maybe one day, JavaFX will actually support the System Tray, but until that day comes, this is the best we got.

**Comment by EasyG0ing1** [comment]
@azplanlos - can't wait to see how you did it ... my experience with AWT is about on par with my lifetime skydiving hours ... which equates to about 20 minutes  ... ☺

**Comment by dustinkredmond** [comment]
@azplanlos , I'm with @EasyG0ing1, I'm fairly versed with JavaFX, but my prior experience with AWT going into the development of this library leaves much to be desired. I look forward to your pull request, and am eager to see your new development. Thank you tons for your contribution!

**Comment by EasyG0ing1** [comment]
@azplanlos 
> I implemented a version supporting CheckMenuItems and will create a pull request shortly.

How is that PR coming along?

**Comment by azplanlos** [comment]
Sorry, I have been busy with some other stuff. PR is on it's way.

**Comment by dustinkredmond** [comment]
Thanks all for the efforts to support CheckMenuItems, this looks great! Closing this issue for now since changes were merged to main.
