### ISSUE TITLE
Will tray closing system works on linux and mac ?

### ISSUE THREAD

**Issue by Jeevasimba** [dustinkredmond/FXTrayIcon#54]
I have a doubt .

Will tray closing system works on linux and mac ?

**Comment by EasyG0ing1** [comment]
@Jeevasimba What do you mean when you say "tray closing system" ?

I use FXTrayIcon in Java Mac apps all the time and it works beautifully ... better than it does in Windows in my humble opinion.

**Comment by Jeevasimba** [comment]
will it work on linux ?

**Comment by Jeevasimba** [comment]
I am using [Style.UNDECORATED][1]  in my javafx application.

In button I set code like this 

    public void exit(ActionEvent event){
        System.exit(0);
    }

If I click that button the tray also closes.

I want to set if I click then the app will go to tray.

How can I set like that with [Style.UNDECORATED][1] ?

  [1]: https://stackoverflow.com/a/8134786/17777351

**Comment by EasyG0ing1** [comment]
@Jeevasimba - First of all, when you instantiate FXTrayIcon, you need to pass in the primaryStage that is created from your Main class 

```
@Override public void start(Stage primaryStage) throws Exception {
    FXTrayIcon trayIcon = new FXTrayIcon.Builder(primaryStage).build();
}
```

Of course you can also include any of your custom build options in that sentence  such as your chosen icon, and your menuItems etc.

When your menuItems call up other windows, they need to have their own Stage associated with their given Scene. Then, when you need to close that window, just call the ```.close()``` method for that Stage

```
myStage.close();
```

**Comment by EasyG0ing1** [comment]
@Jeevasimba - You can [look at this library](https://github.com/EasyG0ing1/SceneOneFX) that I wrote, that makes managing Java Scenes a little easier. With that library, you assign names to your scenes so that you can access them from anywhere in your application. The library lets you create and show a Scene in one line of code, which you can access from anywhere in your program in any class ... closing a Scene is done like this
```
SceneOne.close("MySceneId");
```
The library takes all of the minutiae out of managing scenes.

**Comment by EasyG0ing1** [comment]
@Jeevasimba 

You can use a high quality .png file as your image. Look at the images in the resources folder in the project for some examples. However, in Windows, your image size typically can't be greater than 17 x 17 pixels and usually it needs to be 16 x 16 pixels. On a Mac, you can set it to 22 x 22 pixels and it will look really nice on the mac ... here are some that I use on personal programs that I wrote that run on my mac:
![Screen Shot 2022-05-13 at 10 19 54 AM](https://user-images.githubusercontent.com/10106834/168335999-e53d2beb-d13d-4831-974d-2b8b85aa60c1.png)
