### ISSUE TITLE
Ubuntu 20.04 UnsupportedOperationException: SystemTray icons are not supported

### ISSUE THREAD

**Issue by dpalic** [dustinkredmond/FXTrayIcon#60]
Hi there,

I am about to use FXTrayIcon but facing the issue, that I am getting the Exception

`java.lang.UnsupportedOperationException: SystemTray icons are not supported by the current desktop environment.`

I got the point, that Gnome removed the SystemTray strangely, and I need to install but the system tray is sadly still not working.
So not clear if a package is still missing.

I have already had installed

`sudo apt install gnome-shell-extension-appindicator`

And I have icons in the tray like skype, shutter, Dropbox VLC and so on.

I am willing to support here, to get a fix about this issue. Require only more "directions" how to support, to get SystemTray icons working on Ubuntu
Afaik this is the same case #12

**Comment by dustinkredmond** [comment]
I had dug into trying to support these in the past, but looks like we'd have to download and install a third-party extension to get it working, I'm going to close this issue, preferring to keep the discourse in #12 so that past efforts are visible moving forward. Thanks for opening this issue!
