### ISSUE TITLE
Clicking two time on Tray icon show empty stage?

### ISSUE THREAD

**Issue by ctoabidmaqbool** [dustinkredmond/FXTrayIcon#64]
Hi! When `left double clicking` on TrayIcon with this library then empty stage / window is showing, However in simple AWT codding no such things happens until we set such functionality.

**Comment by dustinkredmond** [comment]
Could you please provide a minimal, reproducible example of the code that exhibits this behavior as well as the code using raw AWT that does *not* cause this issue?

**Comment by dustinkredmond** [comment]
I'm curious as to whether this behavior is present if the `StageStyle` is `UNDECORATED`. E.g:

```java
stage.initStyle(StageStyle.UNDECORATED);
```

**Comment by ctoabidmaqbool** [comment]
@dustinkredmond This is an example which use this lib and have an issue e.g. when double clicking on Tray icon empty stage is opened;
[RunnableTest.java.txt](https://github.com/dustinkredmond/FXTrayIcon/files/9866346/RunnableTest.java.txt)


This one is crated with  simple AWT codding without using any external libs
[RunnableTestAWT.java.txt](https://github.com/dustinkredmond/FXTrayIcon/files/9866348/RunnableTestAWT.java.txt)

**Comment by dustinkredmond** [comment]
Sorry for the delay. I see the issue now. I will release a fix for this in version 4.0.0, scheduled for release later on this evening.
