### ISSUE TITLE
Only square icons possible?

### ISSUE THREAD

**Issue by HanSolo** [dustinkredmond/FXTrayIcon#69]
It looks like in the latest version only square icons are possible (on macos). In the older version I could also use an rectangular icon but in 4.0.1 it only accepts square icons even if I define the icon like 64x32. Is this on purpose?

**Comment by EasyG0ing1** [comment]
@HanSolo - In my experience, MacOD won't even allow icons to be larger than 22 x 22 in the system tray. Though admittedly I haven't tried any rectangular dimensions. Can the system tray even display 64 x 32 without resizing it?

**Comment by HanSolo** [comment]
I did display the rectangular version in an older version of FXTrayIcon but not in the newer version anymore. And yes it will scale down the image (I’ve choosen a higher resolution to get a sharper result because it is text).

**Comment by HanSolo** [comment]
<img width="67" alt="FXTrayIcon_3_1_2" src="https://user-images.githubusercontent.com/62843/206129764-8af3f2e8-01e3-4252-86da-7d868a2e7549.png">
<img width="46" alt="FXTrayIcon_4_0_1" src="https://user-images.githubusercontent.com/62843/206129770-07cbc95e-0631-45b8-b33c-ef0cc358ed07.png">
The first image version is with FXTrayIcon 3.1.2 and the other with 4.0.1, I guess you can see the difference :)

**Comment by EasyG0ing1** [comment]
@HanSolo How are you instantiating? When I try that icon with 3.1.2, it looks like this

![Uploading Screenshot 2022-12-26 at 8.46.45 AM.png…]()

**Comment by EasyG0ing1** [comment]
@HanSolo How are you instantiating FXTrayIcon? When I try that icon with 3.1.2, it looks like this

<img width="37" alt="Screenshot 2022-12-26 at 8 46 45 AM" src="https://user-images.githubusercontent.com/10106834/209569111-951d3a05-2aad-4dd2-a345-fa6abc0d3aa1.png">

This is the icon that I'm using

<img width="67" alt="icon" src="https://user-images.githubusercontent.com/10106834/209569149-5226c293-eb23-481a-92ef-a0c7aa69bca2.png">

Here is the dependency declaration
```Java
        <dependency>
            <groupId>com.dustinredmond.fxtrayicon</groupId>
            <artifactId>FXTrayIcon</artifactId>
            <version>3.1.2</version>
        </dependency>
```

And this is how I'm instantiating
```
FXTrayIcon icon = new FXTrayIcon.Builder(stage,iconurl,22,22).addExitMenuItem().show().build();
```

**Comment by EasyG0ing1** [comment]
@HanSolo I even tried making the same icon with proportional dimensions

![icon](https://user-images.githubusercontent.com/10106834/209571465-cdbcd2ab-729a-48e5-876d-7616482e173e.png)

But I get the same results from 3.1.2 and 4.0.1

Nonetheless, based on What Dustin said about that commit causing the issue, this one here only executes that change if the machine is running Windows so it will not run that code if its being ran on a mac ... try this and see if it doesn't solve the problem:

[FXTrayIcon-4.0.1-SIMS.jar.zip](https://github.com/dustinkredmond/FXTrayIcon/files/10304237/FXTrayIcon-4.0.1-SIMS.jar.zip)

**Comment by HanSolo** [comment]
Sorry, was on vacation and on travel. It looks like the patch from @EasyG0ing1 fixes the issue 👍🏻

**Comment by dustinkredmond** [comment]
Closing issue as @EasyG0ing1 pushed a commit to fix this issue. Looks like it's another one of those issues specific to MacOS.
