### ISSUE TITLE
Maven central version

### ISSUE THREAD

**Issue by gurpal2000** [dustinkredmond/FXTrayIcon#85]
Shows 4.0.1 as  the latest, but main branch is more recent, eg. getRestricted() doesn't exist in 4.0.1

Will there be a new version made available?

btw https://search.maven.org/search?q=g:%22com.dustinredmond.fxtrayicon%22%20AND%20a:%22FXTrayIcon%22 doesn't bring anything useful back.

thanks

**Comment by dustinkredmond** [comment]
I could have sworn I pushed a new release. Let me do that now. Thanks for opening this issue!

**Comment by gurpal2000** [comment]
Yep i usually check on here: https://mvnrepository.com/artifact/com.dustinredmond.fxtrayicon/FXTrayIcon

**Comment by gurpal2000** [comment]
4.2.0 is available - works! Many thanks!
