### ISSUE TITLE
Menu size issue (high dpi)

### ISSUE THREAD

**Issue by gurpal2000** [dustinkredmond/FXTrayIcon#86]
On a Surface pro with res 2736x1824 Windows 11, menu looks like this. Incredibly small relative to the rest of the OS as you can see. Not a major issue and note that some non-Java apps are unable to handle such dpi.

![image](https://github.com/dustinkredmond/FXTrayIcon/assets/169120/3db5edee-4e3e-452e-9e5e-ec472c30817b)

**Comment by EasyG0ing1** [comment]
@gurpal2000 

You can try this one where I added an option to the Builder class, `iconOverride(int width, int height)` you can try that and see if the resolution improves with higher resolution icons under the high resolution desktop. I'm thinking it's not going to make any difference, but it never hurts to try.

Once you've unzipped the archive, you can install it into your local Maven depot:

```bash
mvn install:install-file \
  -Dfile=/full/path/to/FXTrayIcon-4.2.11-SNAPSHOT.jar \
  -DgroupId=com.dustinredmond.fxtrayicon \
  -DartifactId=FXTrayIcon \
  -Dversion=4.2.11-SNAPSHOT \
  -Dpackaging=jar
```

Then your dependency in your POM file:
```xml
<dependency>
   <groupId>com.dustinredmond.fxtrayicon</groupId>
   <artifactId>FXTrayIcon</artifactId>
   <version>4.2.11-SNAPSHOT</version>
</dependency> 
```

Then just instantiate with Builder class calling the `iconOverride` option.
[FXTrayIcon-4.2.11-SNAPSHOT.zip](https://github.com/dustinkredmond/FXTrayIcon/files/15501652/FXTrayIcon-4.2.11-SNAPSHOT.zip)

**Comment by dustinkredmond** [comment]
Any luck here? AWT limits us a good bit as to what we can do here. I would like to close this issue if a resolution has been reached.

**Comment by gurpal2000** [comment]
@dustinkredmond please close as my use case to run on hi dpi no longer exists. The workaround is good enough though and I feel it's a good addition. Considered closed for me, thank you.
